### ISSUE TITLE
mejorar la vista

### ISSUE THREAD

**Issue by EduardoMay** [EduardoMay/bagabundo#13]
En la pagina de inicio de la pagina se debe mostrar los hoteles, autos y atracciones ya con el diseño.

Ruta del archivo php: frontend\views\site\index.php
Lineas: 57 al 77

Utilizar el siguiente componente de bootstrap
Link: https://getbootstrap.com/docs/3.4/components/#thumbnails-custom-content

Dentro de la etiqueta`<div class="thumbnail"></div>`  Se ingresa toda la informacion sacada de la base de datos

Hacer que se vea alineados y responsivo

**Comment by MitchCastro** [comment]
ready
