### ISSUE TITLE
Pagina para la vista de solo hoteles

### ISSUE THREAD

**Issue by EduardoMay** [EduardoMay/bagabundo#14]
Crear con la herramienta de GII, usando el Controller Generator para poder crear la vista de solo hoteles

En las opciones poner lo siguiente:
Controller Class: "frontend\controllers\'NOMBRE'Controller"
Action IDs: Tal cual esta
View Path: Sin datos

Una vez terminado la creacion del Controller, mostrar en la vista Todos los Hoteles

**Comment by maayraa** [comment]
Ya sale la vista, solo faltan la acción de los botones
