### ISSUE TITLE
Pagina para la vista de solo automoviles

### ISSUE THREAD

**Issue by EduardoMay** [EduardoMay/bagabundo#16]
Crear con la herramienta de GII, usando el Controller Generator para poder crear la vista de solo automoviles

En las opciones poner lo siguiente:
Controller Class: "frontend\controllers'NOMBRE'Controller"
Action IDs: Tal cual esta
View Path: Sin datos

Una vez terminado la creacion del Controller, mostrar en la vista Todos los automoviles(Crear una carpeta que se llama Cars, en la ruta de frontend/views/

Basarse en los siguientes rutas:
frontend/controllers/HotelController.php
frontend/views/hotel/index.php

**Comment by Econauta28** [comment]
listo
