### ISSUE TITLE
Traducción en el CRUD de Hoteles - /backend/hotels

### ISSUE THREAD

**Issue by AndreyPootMay** [EduardoMay/bagabundo#19]
El crud de hoteles, atracciones, etc. necesitan estar traducidos al español, puedes utilizar la internacionalización de Yii2 para ello.

- [x] La sintaxis es la siguiente `Yii::t('app', 'Texto traducido').`
- [x] Dentro de un detailview o un gridview basta entrar a las propiedades del array.

_**Ejemplo**_
```
[
 'attribute' => 'Nombre del campo',
 'label' => Yii::t('app', 'Texto traducido')
]

```

**Comment by AndreyPootMay** [comment]
@MitchCastro

**Comment by MitchCastro** [comment]
por revisar @EduardoMay
